# Core
title: Millie Macdonald - Resume & Dev Blog
author: Millie Macdonald
email: milliemacdonald4@gmail.com
description: >
  A blog by Millie Macdonald about her adventures in web development.
baseurl: ""
url: "http://blackcathikari.github.io"

# Build settings
markdown: kramdown

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock